version: '2'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.4"
    volumes:
      # TODO: write in README that this directory should be created before running `docker-compose up` with user ownership
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - '9200:9200'
  
  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:6.8.4"
    environment:
    - server.port=127.0.0.1:5601
    - elasticsearch.url="http://elasticsearch:9200"
    - server.name="kibana"
    depends_on:
    - 'elasticsearch'
    ports:
    - '5601:5601'

  logstash:
    image: "docker.elastic.co/logstash/logstash-oss:6.8.4"
    volumes:
      - ./logstash/config:/config-dir
      - ./logstash/data:/usr/share/logstash/data
    command: logstash -f /config-dir/pipeline.conf
    depends_on:
      - elasticsearch
    ports:
      - "5400" # input directly from parser

  # filebeat:
  #   image: "docker.elastic.co/beats/filebeat-oss:6.8.4"
  #   volumes:
  #     - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - ./filebeat/ApiCommands.log:/usr/share/filebeat/ApiCommands.log
  #   depends_on:
  #   - 'logstash'
  #   command: filebeat -e -strict.perms=false
