version: '2'
services:
  logstash-old-services:
    image: "docker.elastic.co/logstash/logstash-oss:6.8.21"
    volumes:
      - ./logstash/old-services/config:/config-dir:Z
      - ./logstash/old-services/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:Z
      - ./logstash/old-services/data:/usr/share/logstash/data:Z
    command: bash -c "bin/logstash-plugin install logstash-filter-prune && logstash"
    ports:
      - '5400:5400'
      - '9600:9600'
    restart: always

  logstash-new-services:
    environment:
      - ES_LOGSTASH_PASSWORD=${ES_LOGSTASH_PASSWORD}
    image: "docker.elastic.co/logstash/logstash-oss:6.8.21"
    volumes:
      - ./logstash/new-services/config:/config-dir:Z
      - ./logstash/new-services/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:Z
      - ./logstash/new-services/data:/usr/share/logstash/data:Z
    command: bash -c "bin/logstash-plugin install logstash-filter-prune && logstash"
    ports:
      - '5401:5401'
      - '9601:9600'
    restart: always

  logstash-sitesonar:
    environment:
      - ES_LOGSTASH_PASSWORD=${ES_LOGSTASH_PASSWORD}
    image: "docker.elastic.co/logstash/logstash-oss:6.8.21"
    volumes:
      - ./logstash/sitesonar/config:/config-dir:Z
      - ./logstash/sitesonar/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:Z
      - ./logstash/sitesonar/config/log4j2.properties:/usr/share/logstash/config/log4j2.properties:Z
      - ./logstash/sitesonar/data:/usr/share/logstash/data:Z
    command: "logstash"
    ports:
      - '5402:5402'
      - '9602:9600'
    restart: always

  logstash-ccdb:
    environment:
      - ES_LOGSTASH_PASSWORD=${ES_LOGSTASH_PASSWORD}
    image: "docker.elastic.co/logstash/logstash-oss:6.8.21"
    volumes:
      - ./logstash/ccdb/config:/config-dir:Z
      - ./logstash/ccdb/data:/usr/share/logstash/data:Z
    command: logstash -f /config-dir/pipeline.conf
    ports:
      - '5403:5403'
      - '9603:9600'
    restart: always

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.16.1"
    volumes:
      - ./elasticsearch/data:/var/data/elasticsearch
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/logs:/var/logs/elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
      - '9300:9300'
    restart: always

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.16.1"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    restart: always
