version: '2'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.4"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms26G -Xmx26G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
  
  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:6.8.4"
    environment:
    - server.port=127.0.0.1:5601
    - elasticsearch.url="http://elasticsearch:9200"
    - server.name="kibana"
    depends_on:
    - 'elasticsearch'
    ports:
    - '5601:5601'

  logstash-old-services:
    image: "docker.elastic.co/logstash/logstash-oss:6.8.4"
    volumes:
      - ./logstash/old-services/config:/config-dir:Z
      - ./logstash/old-services/data:/usr/share/logstash/data:Z
    command: logstash -f /config-dir/pipeline.conf
    depends_on:
      - elasticsearch
    ports:
      - '5400:5400'

  logstash-new-services:
    image: "docker.elastic.co/logstash/logstash-oss:6.8.4"
    volumes:
      - ./logstash/new-services/config:/config-dir:Z
      - ./logstash/new-services/data:/usr/share/logstash/data:Z
    command: logstash -f /config-dir/pipeline.conf
    depends_on:
      - elasticsearch
    ports:
      - '5401:5401'